title: Yifei Cai
description: Secure, private, and efficient AI systems

theme: jekyll-theme-cayman

show_downloads: false

author:
  name: Yifei Cai
  email: yifeic@iastate.edu
  affiliation: Iowa State University
  github: caiyifei2008
  scholar: https://scholar.google.com/citations?user=zouk6jUAAAAJ&hl=en

nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/

markdown: kramdown
highlighter: rouge
